/**
 * LinkedIn-stijl sector-catalogus voor de ICP webform.
 * Bron: Manus-app (server/icpService.ts).
 */

export const SECTORS: Record<string, string[]> = {
  Technologie: [
    "Software Development",
    "IT Services & IT Consulting",
    "Computer Hardware",
    "Semiconductors",
    "Telecommunications",
    "Internet Publishing",
    "Data Infrastructure & Analytics",
    "Computer Networking Products",
    "Technology, Information & Media",
    "Cybersecurity",
  ],
  "Financiële diensten": [
    "Banking",
    "Insurance",
    "Investment Management",
    "Financial Services",
    "Venture Capital & Private Equity",
    "Accounting",
    "Capital Markets",
    "Credit Intermediation",
    "Leasing Non-residential Real Estate",
  ],
  Gezondheidszorg: [
    "Hospitals & Health Care",
    "Medical Practices",
    "Mental Health Care",
    "Pharmaceutical Manufacturing",
    "Medical Equipment Manufacturing",
    "Biotechnology Research",
    "Wellness & Fitness Services",
    "Veterinary Services",
  ],
  "Productie & Industrie": [
    "Manufacturing",
    "Industrial Machinery Manufacturing",
    "Automation Machinery Manufacturing",
    "Chemical Manufacturing",
    "Food & Beverage Manufacturing",
    "Textile Manufacturing",
    "Plastics Manufacturing",
    "Metal Manufacturing",
    "Printing Services",
  ],
  "Bouw & Vastgoed": [
    "Construction",
    "Real Estate",
    "Architecture & Planning",
    "Civil Engineering",
    "Building Construction",
    "Facilities Services",
    "Landscaping Services",
    "Interior Design",
  ],
  "Retail & E-commerce": [
    "Retail",
    "E-commerce",
    "Wholesale",
    "Luxury Goods & Jewelry",
    "Sporting Goods Manufacturing",
    "Furniture & Home Furnishings",
    "Motor Vehicle Manufacturing",
    "Supermarkets",
  ],
  "Transport & Logistiek": [
    "Freight & Package Transportation",
    "Truck Transportation",
    "Airlines & Aviation",
    "Maritime Transportation",
    "Rail Transportation",
    "Warehousing & Storage",
    "Courier & Package Delivery",
    "Supply Chain Management",
  ],
  "Zakelijke dienstverlening": [
    "Business Consulting & Services",
    "Staffing & Recruiting",
    "Outsourcing & Offshoring Consulting",
    "Human Resources Services",
    "Marketing Services",
    "Advertising Services",
    "Public Relations & Communications Services",
    "Market Research",
    "Translation & Localization",
  ],
  Onderwijs: [
    "Higher Education",
    "Primary & Secondary Education",
    "E-learning Providers",
    "Professional Training & Coaching",
    "Research Services",
    "Libraries",
  ],
  "Media & Entertainment": [
    "Media Production",
    "Broadcast Media Production & Distribution",
    "Publishing",
    "Movies, Videos & Sound",
    "Music",
    "Online Audio & Video Media",
    "Animation & Post-production",
    "Gaming",
    "Spectator Sports",
  ],
  "Overheid & Non-profit": [
    "Government Administration",
    "Public Policy Offices",
    "Non-profit Organizations",
    "International Affairs",
    "Armed Forces",
    "Law Enforcement",
    "Environmental Services",
    "Religious Institutions",
  ],
  "Juridisch & Compliance": [
    "Law Practice",
    "Legal Services",
    "Compliance & Risk Management",
    "Notaries",
    "Patent Attorneys",
  ],
  "Horeca & Toerisme": [
    "Hospitality",
    "Hotels & Motels",
    "Restaurants",
    "Travel Arrangements",
    "Recreational Facilities",
    "Amusement Parks & Arcades",
    "Gambling Facilities & Casinos",
  ],
  "Energie & Milieu": [
    "Oil & Gas",
    "Renewable Energy Semiconductor Manufacturing",
    "Utilities",
    "Environmental Services",
    "Mining",
    "Nuclear Electric Power Generation",
    "Solar Electric Power Generation",
    "Wind Electric Power Generation",
  ],
  "Landbouw & Voedsel": [
    "Farming",
    "Food & Beverage Services",
    "Food & Beverage Manufacturing",
    "Agricultural Chemical Manufacturing",
    "Animal Feed Manufacturing",
    "Fisheries",
  ],
};

export const HOOFDSECTOREN = Object.keys(SECTORS);

export const BEDRIJFSGROOTTES = [
  "1-10 FTE (zzp/start-up)",
  "10-50 FTE (klein MKB)",
  "50-250 FTE (middelgroot MKB)",
  "250-1000 FTE (groot MKB)",
  "1000+ FTE (enterprise)",
];

export const VINDKANALEN = [
  "Google Search",
  "LinkedIn",
  "Beurzen / events",
  "Vakmedia",
  "Referrals / mond-tot-mond",
  "Cold outreach (e-mail / telefoon)",
  "Branche-organisaties",
  "Partner-netwerk",
  "Eigen content / SEO",
  "Webinars / podcasts",
];
